# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Form_layout.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from Part1 import *
class Ui_Form(object):
    def __init__(self):
        self.name= None 
        self.address=None
        self.city=None
        self.qualification=None
        self.gender=None
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.line1 = QtWidgets.QLineEdit(Form)
        self.line1.setObjectName("line1")
        self.gridLayout.addWidget(self.line1, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 1, 1, 1)
        self.line4 = QtWidgets.QLineEdit(Form)
        self.line4.setObjectName("line4")
        self.gridLayout.addWidget(self.line4, 4, 2, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line3 = QtWidgets.QLineEdit(Form)
        self.line3.setObjectName("line3")
        self.verticalLayout.addWidget(self.line3)
        self.gridLayout.addLayout(self.verticalLayout, 2, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.RadioB1 = QtWidgets.QRadioButton(Form)
        self.RadioB1.setObjectName("RadioB1")
        self.horizontalLayout.addWidget(self.RadioB1)
        self.RadioB2 = QtWidgets.QRadioButton(Form)
        self.RadioB2.setObjectName("RadioB2")
        self.horizontalLayout.addWidget(self.RadioB2)
        self.gridLayout.addLayout(self.horizontalLayout, 5, 2, 1, 1)
        self.Button1 = QtWidgets.QPushButton(Form)
        self.Button1.setObjectName("Button1")
        self.gridLayout.addWidget(self.Button1, 6, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 1, 1, 1)
        self.Button2 = QtWidgets.QPushButton(Form)
        self.Button2.setObjectName("Button2")
        self.gridLayout.addWidget(self.Button2, 7, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 1, 1, 1)
        self.line2 = QtWidgets.QLineEdit(Form)
        self.line2.setObjectName("line2")
        self.gridLayout.addWidget(self.line2, 1, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)

        self.retranslateUi(Form)
        self.Button1.clicked.connect(self.line4.clear)
        self.Button1.clicked.connect(self.line2.clear)
        self.Button1.clicked.connect(self.line3.clear)
        self.Button1.clicked.connect(self.line1.clear)
        QtCore.QMetaObject.connectSlotsByName(Form)
        self.Button2.clicked.connect(self.data)
        self.RadioB2.clicked.connect(self.gender1)
        self.RadioB1.clicked.connect(self.gender2)
        self.Button2.clicked.connect(self.database)
       
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Name"))
        self.label_4.setText(_translate("Form", "gender"))
        self.RadioB1.setText(_translate("Form", "F"))
        self.RadioB2.setText(_translate("Form", "M"))
        self.Button1.setText(_translate("Form", "reset"))
        self.label_3.setText(_translate("Form", "qualification"))
        self.Button2.setText(_translate("Form", "ok"))
        self.label_2.setText(_translate("Form", "Address"))
        self.label_5.setText(_translate("Form", "City"))
    def data(self):
        self.name=self.line1.text()
        self.address=self.line2.text()
        self.city=self.line3.text()
        self.qualification=self.line4.text()
        #print(self.name)
        
    def getname(self):
              return self.name
    def getaddress(self):
              return self.address
    def getcity(self):
              return self.city
    def getqualification(self):
              return self.qualification
    def getgender(self):
        return self.gender
        
    def gender1(self):
              self.gender='M'
              #print("gender run:"+self.gender)
    def gender2(self):
              self.gender='F'
              #print("gender run:"+self.gender)
    def database(self):
        #print("dataBase")
        Dbms.querry(self.getname(),self.getaddress(),self.getcity(),self.getqualification(),self.getgender())


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
    

'''name=input("enter the name=")
    address=input("enter the address=")
    city=input("enter the city=")
    qualification=input("enter the qualification")
    gender=input("enter the gender=")'''
